name: Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install
        working-directory: ./test

      - name: Lancer les tests
        run: npm test
        working-directory: ./test
